development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: mn_production
  pool: 5
  username: blog
  password: mn_dev

test:
  adapter: postgresql
  encoding: unicode
  database: mn_test
  pool: 5
  username: blog
  password: mn_dev