development:
  adapter: postgresql
  encoding: unicode
  database: mn_development
  pool: 5
  username: blog
  password: mn_dev

production:
  adapter: postgresql
  encoding: unicode
  database: mn_production
  pool: 5
  username: blog
  password: mn_dev

test:
  adapter: postgresql
  encoding: unicode
  database: mn_test
  pool: 5
  username: blog
  password: mn_dev